- name: Ensure Rabbit Group
  ansible.builtin.group:
    name: rabbit
    state: present
    system: false

- name: Create rabbit user
  ansible.builtin.user:
    name: rabbit
    groups: rabbit
    append: true
    shell: /bin/bash
    state: present
    create_home: true
    generate_ssh_key: false

- name: Ensure .ssh directory
  ansible.builtin.file:
    path: /home/rabbit/.ssh
    state: directory
    mode: "0700"
    owner: rabbit
    group: rabbit

- name: Set private key
  ansible.builtin.copy:
    dest: "/home/rabbit/.ssh/{{ item.dest }}"
    content: "{{ item.src }}"
    backup: true
    mode: "0444"
    owner: rabbit
    group: rabbit
  loop:
    - src: "{{ rabbitmq_secret.data.data.ssh_private_key }}"
      dest: id_rsa
    - src: "{{ rabbitmq_secret.data.data.ssh_public_key }}"
      dest: id_rsa.pub
  no_log: true

- name: Set up authorized_key
  ansible.posix.authorized_key:
    user: rabbit
    key: "{{ rabbitmq_secret.data.data.ssh_public_key }}"
    path: /home/rabbit/authorized_keys
    manage_dir: false
    state: present
    exclusive: false
