---
name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.17.0
        with:
          path: test/playbook.yml
        env:
          ANSIBLE_ROLES_PATH: "${PWD}/../"
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: add semantic release plugins
        run: |
          npm install -D '@semantic-release/changelog' \
                          '@semantic-release/git'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
